import Head from 'next/head'
import Link from 'next/link'
import Auth from '../modules/supabase/components/Auth'
import Account from '../modules/supabase/components/Account'
import { useState, useEffect } from 'react'
import { supabase } from '../modules/supabase/client'
import { Session } from '@supabase/supabase-js'



export default function Home() {

  const [session, setSession] = useState<Session | null>(null);

  useEffect(() => {
    setSession(supabase.auth.session());
    supabase.auth.onAuthStateChange((_event, session) => {
      setSession(session)
    })
  }, [])

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='underline'>
          AFL Tipping with <a href="https://nextjs.org">Next.js!</a>
        </h1>


        <hr />

        <p>Auth0</p>

        <Link href='/api/auth/login'>Login</Link>
        <Link href='/api/auth/logout'>Logout</Link>

        <p>Supabase</p>

        <div className='container' style={{ padding: '50px 0 100px 0' }}>
          {!session ? <Auth /> : <Account key={session!.user!.id} session={session} />}
        </div>




      </main>
    </div>
  )
}

