import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { GamesResponse, getGames, getLocalGames } from '../lib/games'
import { AppConfig } from '../lib/app.config'
import { RoundManager } from '../lib/picker'
import { SelectTips } from '../components/tipping'
import { Round } from '../lib/squiggle/db'

export const getStaticProps: GetStaticProps = async () => {
  //const res = await fetch(`${AppConfig.aflEndpoint}?q=games;year=${new Date().getFullYear()};round=${5}`)
  //const games: GamesResponse = await res.json()
  const key = `games;year=${new Date().getFullYear().toString()};round=${5}`;
  let games = {};
  if (AppConfig.local) {
    games = await getLocalGames('5');
  } else {
    let _games = await Round(5);
    console.log(JSON.stringify(_games));
    games = await getGames(key);
  }

  return {
    props: {
      games
    }
  }
}

export default function Home({ games }: { games: GamesResponse }) {

  const gamesList = [{ homeTeam: 'Brisbane', awayTeam: 'Collingwood' }, { homeTeam: 'North Melbourne', awayTeam: 'Bulldogs' }, { homeTeam: 'West Coast', awayTeam: 'Sydney' }, { homeTeam: 'St Kilda', awayTeam: 'Gold Coast' }];

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='underline'>
          AFL Tipping with <a href="https://nextjs.org">Next.js!</a>
        </h1>

        {games.games ? (
          games.games!.map((game) => <li key={game.id}>{game.ateam} vs. {game.hteam} at {game.date}</li>)

        ) : (
          <p>Games data missing</p>
        )}

        <hr />

        <a href='/api/auth/login'>Login</a>
        <a href='/api/auth/logout'>Logout</a>

        <hr />

        <SelectTips games={gamesList} />


      </main>
    </div>
  )
}

