import type { GetStaticProps, NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import { GamesResponse, getGames } from '../lib/games'
import { AppConfig } from '../lib/app.config'
import { SelectTips } from '../components/tipping'
import { Round } from '../lib/squiggle/db'
import Link from 'next/link'
import prisma from '../lib/prisma'
import { Prisma } from '@prisma/client'

export const getStaticProps: GetStaticProps = async () => {
  //const res = await fetch(`${AppConfig.aflEndpoint}?q=games;year=${new Date().getFullYear()};round=${5}`)
  //const games: GamesResponse = await res.json()
  const key = `games;year=${new Date().getFullYear().toString()};round=${5}`;
  let games = {};
  if (AppConfig.local) {
    const gameSelect: Prisma.GameSelect = {
      homeTeam: {
        select: { name: true }
      },
      awayTeam: {
        select: {
          name: true
        }
      }
    };

    const games = await prisma.game.findMany({
      where: { round: { year: new Date().getFullYear(), round: AppConfig.round } }, select: gameSelect,
    });

    return { props: { games } };
  } else {
    throw new Error('unimplemented')
  }

}

export default function Home({ games }: { games: { homeTeam: { name: string }, awayTeam: { name: string } }[] }) {
  let gamesList = games.map((game => { let simplifiedGame = { homeTeam: game.homeTeam.name, awayTeam: game.awayTeam.name }; return simplifiedGame; }));

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className='underline'>
          AFL Tipping with <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <ol>
          {gamesList.map((game) => <li key={game.homeTeam}>{game.homeTeam} vs. {game.awayTeam}</li>)}
        </ol>

        <hr />

        <Link href='/api/auth/login'>Login</Link>
        <Link href='/api/auth/logout'>Logout</Link>

        <hr />

        <SelectTips games={gamesList} />


      </main>
    </div>
  )
}

